application: flyingonwheel
version: 4
runtime: python
api_version: 1

handlers:
- url: /style.css
  static_files: style.css
  upload: style.css

- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /gaeutilities/.*
  script: appengine_utilities/interface/main.py
  login: admin

- url: .*
  script: main.py
  secure: optional
